# -*- coding: utf-8 -*-
"""Students.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18lA2Bf1vkK2obd_BclVSRSE53Kf0Qm8-
"""

# students.py

class Student:
    def __init__(self, student_id, name, age, subjects):
        self.student_id = student_id
        self.name = name
        self.age = age
        self.subjects = subjects

    def add_subject(self, subject):
        self.subjects.append(subject)

    def remove_subject(self, subject):
        if subject in self.subjects:
            self.subjects.remove(subject)

    def update_info(self, name=None, age=None, subjects=None):
        if name is not None:
            self.name = name
        if age is not None:
            self.age = age
        if subjects is not None:
            self.subjects = subjects

    def __str__(self):
        return f"Student ID: {self.student_id}, Name: {self.name}, Age: {self.age}, Subjects: {', '.join(self.subjects)}"


def main():
    students = [
        Student(1, "John Doe", 20, ["Math", "Science"]),
        Student(2, "Jane Smith", 21, ["History", "English"]),
        Student(3, "Emily Davis", 22, ["Biology", "Chemistry"])
    ]

    for student in students:
        print(student)

    print("\nUpdating John's age and subjects...\n")
    students[0].update_info(age=21, subjects=["Math", "Science", "Art"])

    for student in students:
        print(student)


if __name__ == "__main__":
    main()
